language: node_js
sudo: false
node_js:
  - 12
  - 11
  - 10
  - 9
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
  - sudo apt-get update
install:
  - npm install
script:
  - npm run test
  - npm run test:coverage
