name: build

on:
  - push
  - pull_request

jobs:
  createAndTestTemplateCRA:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Create CRA from downloaded template
        run: npx create-react-app --template cra-template-must-have-libraries .
      - run: npm run build
